# Generated by Django 5.2.8 on 2025-11-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
